### ISSUE TITLE
Next.js

### ISSUE THREAD

**Issue by nbeers22** [Sitefinity/react-standalone-renderer#16]
I see you had Next.js in there and then decided to remove it. What is the reasoning behind that? Hardly anyone uses plain React these days, and even the maintainers of React itself say you should be using Next or Remix. This is now unusable without SSR.

**Comment by Gebov** [comment]
@nbeers22 we seperated them into two repositories. [Here ](https://github.com/Sitefinity/nextjs-renderer)is the next.js one

**Comment by nbeers22** [comment]
Thank you. I saw that after I commented, so I closed it out.
